[project]
name = "0xproto-build"
version = "0.0.0"
requires-python = ">=3.10"
dependencies = [
    "fontmake>=3.11.1",
    "fonttools>=4.61.1",
    "glyphsLib>=6.12.6",
    "ttfautohint-py>=0.6.0",
]
[dependency-groups]
dev = [
    "fontbakery>=1.1.0",
]
